# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './interfaces/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .login import Ui_login
from .signup import Ui_signup

class Ui_initialWindow(object):

    def toLogin(self):
        self.login = QtWidgets.QMainWindow()
        self.instance = Ui_login()
        self.instance.setupUi(self.login)
        self.login.show()

    def toSignup(self):
        self.signup = QtWidgets.QMainWindow()
        self.instance = Ui_signup()
        self.instance.setupUi(self.signup)
        self.signup.show()

    def setupUi(self, initialWindow):
        initialWindow.setObjectName("initialWindow")
        initialWindow.resize(625, 504)
        initialWindow.setMinimumSize(QtCore.QSize(625, 504))
        initialWindow.setMaximumSize(QtCore.QSize(625, 504))
        initialWindow.setDocumentMode(False)
        self.mainframe = QtWidgets.QWidget(initialWindow)
        self.mainframe.setObjectName("mainframe")
        self.Title = QtWidgets.QLabel(self.mainframe)
        self.Title.setGeometry(QtCore.QRect(100, 40, 461, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Title.setFont(font)
        self.Title.setTextFormat(QtCore.Qt.RichText)
        self.Title.setScaledContents(False)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.subtitle = QtWidgets.QLabel(self.mainframe)
        self.subtitle.setGeometry(QtCore.QRect(180, 120, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subtitle.setFont(font)
        self.subtitle.setTextFormat(QtCore.Qt.RichText)
        self.subtitle.setScaledContents(False)
        self.subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.loginButton = QtWidgets.QPushButton(self.mainframe)
        self.loginButton.setGeometry(QtCore.QRect(180, 220, 291, 61))
        self.loginButton.setStyleSheet("font-size: 20px;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/svgs/solid/right-from-bracket.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon)
        self.loginButton.setObjectName("loginButton")
        self.loginButton.clicked.connect(self.toLogin)
        self.loginButton.clicked.connect(initialWindow.close)

        self.registerButton = QtWidgets.QPushButton(self.mainframe)
        self.registerButton.setGeometry(QtCore.QRect(180, 300, 291, 61))
        self.registerButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.registerButton.setStyleSheet("font-size: 20px;")
        self.registerButton.setIcon(icon)
        self.registerButton.setObjectName("registerButton")
        self.registerButton.clicked.connect(self.toSignup)
        self.registerButton.clicked.connect(initialWindow.close)
        initialWindow.setCentralWidget(self.mainframe)

        self.retranslateUi(initialWindow)
        QtCore.QMetaObject.connectSlotsByName(initialWindow)

    def retranslateUi(self, initialWindow):
        _translate = QtCore.QCoreApplication.translate
        initialWindow.setWindowTitle(_translate("initialWindow", "Consultation System"))
        self.Title.setText(_translate("initialWindow", "Consultation System"))
        self.subtitle.setText(_translate("initialWindow", "Manage your time for your students in just one click."))
        self.loginButton.setText(_translate("initialWindow", "Login"))
        self.registerButton.setText(_translate("initialWindow", "Sign Up"))
        
import resources_rc
