name: Update Changelog
on:
  push:
    branches:
      - '*'

jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking changes
      uses: actions/checkout@v2

    - name: Creating environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Update Changelog
      run: |
        echo "- Commit: \${{ github.sha }}" >> CHANGELOG.md
        echo "  Author: \${{ github.event.head_commit.author.name }}" >> CHANGELOG.md
        echo "  Message: \${{ github.event.head_commit.message }}" >> CHANGELOG.md
        echo "  Date: $(date +"%Y-%m-%d")" >> CHANGELOG.md
        echo "" >> CHANGELOG.md
