name: Update Changelog
on:
  push:
    branches:
      - '*'

jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Changelog
      run: |
        branch_name=${GITHUB_REF#refs/heads/}
        changelog_file="CHANGELOG-${branch_name^^}.md"

        echo "## Changelog" > "$changelog_file"
        echo "- Author: ${{ github.actor }}" >> "$changelog_file"
        echo "  Commit: ${{ github.sha }}" >> "$changelog_file"
        echo "  Message: ${{ github.event.head_commit.message }}" >> "$changelog_file"
        echo "  Date: $(date +"%Y-%m-%d")" >> "$changelog_file"
        cat "$changelog_file"

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        branch_name=${GITHUB_REF#refs/heads/}
        changelog_file="CHANGELOG-${branch_name^^}.md"
        git add "$changelog_file"
        git commit -m "Update $changelog_file"
        git push
