name: Update Changelog
on:
  push:
    branches:
      - '*'

jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Changelog
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const changelogPath = './CHANGELOG.md';
          const commitAuthor = github.context.payload.head_commit.author.name;
          const commitHash = github.context.sha;
          const commitMessage = github.context.payload.head_commit.message;
          const currentDate = new Date().toISOString().split('T')[0];

          const changelogContent = `- Author: ${commitAuthor}\n  Commit: ${commitHash}\n  Message: ${commitMessage}\n  Date: ${currentDate}\n`;

          fs.appendFileSync(changelogPath, changelogContent);
